version: '3'
services:
  postgres:
    build:
      context: .
      dockerfile: DockerfilePostgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jaeger-storage
    ports:
      - '5432:5432'
    networks:
      - shared-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d jaeger-storage" ]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 10s
  neo4j:
    image: neo4j:5.22
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data:/data
      - ./plugins:/plugins
    environment:
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
      NEO4J_PLUGINS: '["apoc","apoc-extended"]'
      NEO4J_AUTH: "none"
    networks:
      - shared-network
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 10s
  jaeger-storage:
    image: coms559/jaeger-storage
    build:
      context: .
      dockerfile: DockerfileGo
    ports:
      - '54321:54321'
    depends_on:
      postgres:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    networks:
      - shared-network
    environment:
      POSTGRES_HOST: 'postgres'
      NEO4J_URI: 'bolt://neo4j:7687'
      OPENAI_API_KEY: '${OPENAI_API_KEY}'

networks:
  shared-network:
    driver: bridge
